---
- name: clickhouse
  src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"

- name: lighthouse-role
  src: git@github.com:Jlljully/lighthouse-role.git
  scm: git
  version: "1.13"

- name: vector-role
  src: git@github.com:Jlljully/vector-role.git
  scm: git
  version: "1.13"

