---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.119.246
      ansible_user: centos

vector:
  hosts:
    vector-01:
      ansible_host: 51.250.80.23
      ansible_user: centos

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.104.122
      ansible_user: centos

