---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.87.144
      ansible_user: centos

vector:
  hosts:
    vector-01:
      ansible_host: 158.160.32.58
      ansible_user: centos

